export const FETCH_MENU_BY_CATEGORY = "FETCH_MENU_BY_CATEGORY";
export const SELECT_MENU = "SELECT_MENU";
export const SELECT_MULTIPLIER = "SELECT_MULTIPLIER";
export const ADD_TO_ORDER = "ADD_TO_ORDER";